import { Branches, Locations, VehicleBrands, VehicleModels, VehicleVariants, VehicleBodyTypes, VehicleFeatures, PartBrands, PartCategories, TireBrands, TireModels } from "@bigmotors/sysop-dti";
import { apiClient } from "../../api/client";
import type { ReferenceDefinition } from "./model";

export const referenceDefinitions: Record<string, ReferenceDefinition> = {
  "branches": {
    slug: "branches", title: "Салбар",
    createSchema: Branches.createBody, updateSchema: Branches.updateBody, querySchema: Branches.listQuery,
    list: (query, signal) => apiClient.call(Branches.list, { query: Branches.listQuery.parse(query) }, { signal }),
    create: (input) => apiClient.call(Branches.create, { body: Branches.createBody.parse(input) }),
    update: (id, input) => apiClient.call(Branches.update, { params: { id }, body: Branches.updateBody.parse(input) }),
    remove: (id) => apiClient.call(Branches.remove, { params: { id } }),
  },
  "locations": {
    slug: "locations", title: "Бүтээгдэхүүний байршил",
    createSchema: Locations.createBody, updateSchema: Locations.updateBody, querySchema: Locations.listQuery,
    list: (query, signal) => apiClient.call(Locations.list, { query: Locations.listQuery.parse(query) }, { signal }),
    create: (input) => apiClient.call(Locations.create, { body: Locations.createBody.parse(input) }),
    update: (id, input) => apiClient.call(Locations.update, { params: { id }, body: Locations.updateBody.parse(input) }),
    remove: (id) => apiClient.call(Locations.remove, { params: { id } }),
  },
  "vehicle-brands": {
    slug: "vehicle-brands", title: "Автомашины марк",
    createSchema: VehicleBrands.createBody, updateSchema: VehicleBrands.updateBody, querySchema: VehicleBrands.listQuery,
    list: (query, signal) => apiClient.call(VehicleBrands.list, { query: VehicleBrands.listQuery.parse(query) }, { signal }),
    create: (input) => apiClient.call(VehicleBrands.create, { body: VehicleBrands.createBody.parse(input) }),
    update: (id, input) => apiClient.call(VehicleBrands.update, { params: { id }, body: VehicleBrands.updateBody.parse(input) }),
    remove: (id) => apiClient.call(VehicleBrands.remove, { params: { id } }),
  },
  "vehicle-models": {
    slug: "vehicle-models", title: "Автомашины загвар",
    parent: { key: "brandId", label: "Автомашины марк", source: "vehicle-brands" },
    createSchema: VehicleModels.createBody, updateSchema: VehicleModels.updateBody, querySchema: VehicleModels.listQuery,
    list: (query, signal) => apiClient.call(VehicleModels.list, { query: VehicleModels.listQuery.parse(query) }, { signal }),
    create: (input) => apiClient.call(VehicleModels.create, { body: VehicleModels.createBody.parse(input) }),
    update: (id, input) => apiClient.call(VehicleModels.update, { params: { id }, body: VehicleModels.updateBody.parse(input) }),
    remove: (id) => apiClient.call(VehicleModels.remove, { params: { id } }),
  },
  "vehicle-variants": {
    slug: "vehicle-variants", title: "Хувилбар",
    parent: { key: "modelId", label: "Автомашины загвар", source: "vehicle-models" },
    createSchema: VehicleVariants.createBody, updateSchema: VehicleVariants.updateBody, querySchema: VehicleVariants.listQuery,
    list: (query, signal) => apiClient.call(VehicleVariants.list, { query: VehicleVariants.listQuery.parse(query) }, { signal }),
    create: (input) => apiClient.call(VehicleVariants.create, { body: VehicleVariants.createBody.parse(input) }),
    update: (id, input) => apiClient.call(VehicleVariants.update, { params: { id }, body: VehicleVariants.updateBody.parse(input) }),
    remove: (id) => apiClient.call(VehicleVariants.remove, { params: { id } }),
  },
  "vehicle-body-types": {
    slug: "vehicle-body-types", title: "Кузовын төрөл",
    createSchema: VehicleBodyTypes.createBody, updateSchema: VehicleBodyTypes.updateBody, querySchema: VehicleBodyTypes.listQuery,
    list: (query, signal) => apiClient.call(VehicleBodyTypes.list, { query: VehicleBodyTypes.listQuery.parse(query) }, { signal }),
    create: (input) => apiClient.call(VehicleBodyTypes.create, { body: VehicleBodyTypes.createBody.parse(input) }),
    update: (id, input) => apiClient.call(VehicleBodyTypes.update, { params: { id }, body: VehicleBodyTypes.updateBody.parse(input) }),
    remove: (id) => apiClient.call(VehicleBodyTypes.remove, { params: { id } }),
  },
  "vehicle-features": {
    slug: "vehicle-features", title: "Тоноглол",
    createSchema: VehicleFeatures.createBody, updateSchema: VehicleFeatures.updateBody, querySchema: VehicleFeatures.listQuery,
    list: (query, signal) => apiClient.call(VehicleFeatures.list, { query: VehicleFeatures.listQuery.parse(query) }, { signal }),
    create: (input) => apiClient.call(VehicleFeatures.create, { body: VehicleFeatures.createBody.parse(input) }),
    update: (id, input) => apiClient.call(VehicleFeatures.update, { params: { id }, body: VehicleFeatures.updateBody.parse(input) }),
    remove: (id) => apiClient.call(VehicleFeatures.remove, { params: { id } }),
  },
  "part-brands": {
    slug: "part-brands", title: "Сэлбэгийн брэнд",
    createSchema: PartBrands.createBody, updateSchema: PartBrands.updateBody, querySchema: PartBrands.listQuery,
    list: (query, signal) => apiClient.call(PartBrands.list, { query: PartBrands.listQuery.parse(query) }, { signal }),
    create: (input) => apiClient.call(PartBrands.create, { body: PartBrands.createBody.parse(input) }),
    update: (id, input) => apiClient.call(PartBrands.update, { params: { id }, body: PartBrands.updateBody.parse(input) }),
    remove: (id) => apiClient.call(PartBrands.remove, { params: { id } }),
  },
  "part-categories": {
    slug: "part-categories", title: "Сэлбэгийн ангилал",
    parent: { key: "parentId", label: "Дээд ангилал", source: "part-categories", optional: true },
    createSchema: PartCategories.createBody, updateSchema: PartCategories.updateBody, querySchema: PartCategories.listQuery,
    list: (query, signal) => apiClient.call(PartCategories.list, { query: PartCategories.listQuery.parse(query) }, { signal }),
    create: (input) => apiClient.call(PartCategories.create, { body: PartCategories.createBody.parse(input) }),
    update: (id, input) => apiClient.call(PartCategories.update, { params: { id }, body: PartCategories.updateBody.parse(input) }),
    remove: (id) => apiClient.call(PartCategories.remove, { params: { id } }),
  },
  "tire-brands": {
    slug: "tire-brands", title: "Дугуйн брэнд",
    createSchema: TireBrands.createBody, updateSchema: TireBrands.updateBody, querySchema: TireBrands.listQuery,
    list: (query, signal) => apiClient.call(TireBrands.list, { query: TireBrands.listQuery.parse(query) }, { signal }),
    create: (input) => apiClient.call(TireBrands.create, { body: TireBrands.createBody.parse(input) }),
    update: (id, input) => apiClient.call(TireBrands.update, { params: { id }, body: TireBrands.updateBody.parse(input) }),
    remove: (id) => apiClient.call(TireBrands.remove, { params: { id } }),
  },
  "tire-models": {
    slug: "tire-models", title: "Дугуйн загвар",
    parent: { key: "brandId", label: "Дугуйн брэнд", source: "tire-brands" },
    createSchema: TireModels.createBody, updateSchema: TireModels.updateBody, querySchema: TireModels.listQuery,
    list: (query, signal) => apiClient.call(TireModels.list, { query: TireModels.listQuery.parse(query) }, { signal }),
    create: (input) => apiClient.call(TireModels.create, { body: TireModels.createBody.parse(input) }),
    update: (id, input) => apiClient.call(TireModels.update, { params: { id }, body: TireModels.updateBody.parse(input) }),
    remove: (id) => apiClient.call(TireModels.remove, { params: { id } }),
  },
};

