import assert from "node:assert/strict";
import { randomUUID } from "node:crypto";
import { once } from "node:events";
import { createServer } from "node:http";
import { test } from "node:test";
import { fileURLToPath } from "node:url";
import { PGlite } from "@electric-sql/pglite";
import { TKN_DB, type BigMotorsDb } from "@bigmotors/db";
import * as schema from "@bigmotors/db/schema";
import { Galleries, GalleryItems } from "@bigmotors/sysop-dti";
import { drizzle } from "drizzle-orm/pglite";
import { migrate } from "drizzle-orm/pglite/migrator";
import { createApp } from "../src/app.js";
import { createContainer } from "../src/di.js";

test("gallery HTTP CRUD uses production DI, contracts and file usage triggers", async (t) => {
  const db = new PGlite(); const root = createContainer({ env: {} }); const orm = drizzle(db, { schema });
  const di = root.child("gallery-http").asValue(TKN_DB, orm as unknown as BigMotorsDb);
  const server = createServer(createApp(di));
  t.after(async () => {
    if (server.listening) await new Promise<void>((resolve) => { server.close(() => resolve()); server.closeAllConnections(); });
    root.destroy(); await db.close();
  });
  await migrate(orm, { migrationsFolder: fileURLToPath(new URL("../../../packages/db/migrations/", import.meta.url)) });
  server.listen(0, "127.0.0.1"); await once(server, "listening");
  const address = server.address(); assert.ok(address && typeof address !== "string");
  async function request(method: string, path: string, body?: unknown, status = 200) {
    const response = await fetch(`http://127.0.0.1:${(address as {port:number}).port}/api${path}`, { method, ...(body === undefined ? {} : { headers: {"Content-Type":"application/json"}, body: JSON.stringify(body) }) });
    const result = await response.json() as { success: boolean; data?: unknown; code?: string; stack?: unknown };
    assert.equal(response.status, status, JSON.stringify(result));
    assert.equal(result.success, status === 200); assert.equal(result.stack, undefined);
    return status === 200 ? result.data : result.code;
  }
  const g = Galleries.entity.parse(await request("POST", "/galleries", { key: " http-banner ", name: "HTTP gallery" }));
  assert.equal(g.key, "http-banner");
  assert.deepEqual(Galleries.entity.parse(await request("GET", `/galleries/${g.id}`)), g);
  assert.equal(Galleries.listResult.parse(await request("GET", "/galleries?search=HTTP&limit=1")).length, 1);
  assert.equal((Galleries.entity.parse(await request("PATCH", `/galleries/${g.id}`, { desc: "changed" }))).desc, "changed");
  await request("POST", "/galleries", { name: "Missing key" }, 400);
  await request("PATCH", `/galleries/${g.id}`, { key: " " }, 400);
  assert.equal(await request("POST", "/galleries", { key: g.key, name: "Duplicate" }, 409), "GALLERY_KEY_CONFLICT");
  const other = Galleries.entity.parse(await request("POST", "/galleries", { key: "other", name: "Other" }));
  assert.equal(await request("PATCH", `/galleries/${other.id}`, { key: g.key }, 409), "GALLERY_KEY_CONFLICT");
  assert.equal(Galleries.entity.parse(await request("PATCH", `/galleries/${other.id}`, { key: "renamed" })).key, "renamed");
  assert.equal(Galleries.listResult.parse(await request("GET", "/galleries?search=renamed"))[0]?.id, other.id);
  await request("DELETE", `/galleries/${other.id}`);
  await request("POST", "/galleries", { name: " " }, 400);
  await request("GET", "/galleries?offset=-1", undefined, 400);
  const imageId = randomUUID();
  await db.query("INSERT INTO files (id,file_path,original_name) VALUES ($1,'gallery/http','http.jpg')", [imageId]);
  const path = `/galleries/${g.id}/items`;
  const item = GalleryItems.entity.parse(await request("POST", path, { imageId, title: "Photo", linkUrl: "/vehicles", linkLabel: "Catalog" }));
  assert.equal(item.linkUrl, "/vehicles"); assert.equal(item.linkLabel, "Catalog");
  assert.equal(GalleryItems.listResult.parse(await request("GET", path))[0]?.linkUrl, "/vehicles");
  assert.equal(GalleryItems.listResult.parse(await request("GET", path))[0]?.originalName, "http.jpg");
  const updated = GalleryItems.entity.parse(await request("PATCH", `${path}/${item.id}`, { sortOrder: 9, label: "New" }));
  assert.equal(updated.sortOrder, 9);
  assert.equal(updated.linkUrl, "/vehicles");
  await request("PATCH", `${path}/${item.id}`, { linkUrl: "javascript:alert(1)" }, 400);
  const cleared = GalleryItems.entity.parse(await request("PATCH", `${path}/${item.id}`, { linkUrl: "", linkLabel: null }));
  assert.equal(cleared.linkUrl, null); assert.equal(cleared.linkLabel, null);
  await request("PATCH", `${path}/${item.id}`, { imageId: randomUUID(), title: "Replacement" }, 400);
  assert.equal(GalleryItems.listResult.parse(await request("GET", path))[0]?.imageId, imageId);
  await request("PATCH", `/galleries/${randomUUID()}/items/${item.id}`, { label: "Wrong" }, 404);
  await request("POST", path, { imageId: randomUUID() }, 409);
  await request("PATCH", `${path}/${item.id}`, {}, 400);
  assert.equal(GalleryItems.entity.parse(await request("DELETE", `${path}/${item.id}`)).id, item.id);
  await request("POST", path, { imageId });
  await request("DELETE", `/galleries/${g.id}`);
  await request("GET", `/galleries/${g.id}`, undefined, 404);
  assert.deepEqual((await db.query("SELECT usage FROM files WHERE id=$1", [imageId])).rows, [{ usage: [] }]);
});
